name: MCOHexRoyale
version: '1.0'
main: net.mcoasis.mcohexroyale.MCOHexRoyale
api-version: '1.21'
authors: [ LazyGamer21 ]
depend: [ WorldEdit ]

commands:
  mcohexroyale:
    description: Main command for HexRoyale
    usage: /mcohexroyale
    permission: hexroyale.admin

permissions:
  hexroyale.admin:
    default: false
  hexroyale.nojoin:
    default: false