name: MCOHexRoyale
version: '1.0'
main: net.mcoasis.mcohexroyale.MCOHexRoyale
api-version: '1.21'
authors: [ LazyGamer21 ]
depend: [ WorldEdit ]
softdepend: [ PlaceholderAPI ]

commands:
  mcohexroyale:
    description: Main command for HexRoyale
    usage: /mcohexroyale
    permission: hexroyale.admin
  setteam:
    description: set a player's team
    usage: /setteam <player> <team>
    permission: hexroyale.admin
  teamchat:
    description: chat only player's on same hex team can see
    usage: /teamchat
    aliases: tc
  shop:
    description: opens player shop to buy/sell stuff
    usage: /shop
    permission: hexroyale.shop
  setmiddlespawn:
    description: sets the middle tile spawn location
    usage: /setmiddlespawn
    permission: hexroyale.admin
  chooseteam:
    description: let participants choose their team
    permission: hexroyale.chooseteam

permissions:
  hexroyale.admin:
    default: false
  hexroyale.nojoin:
    default: false
  hexroyale.shop:
    default: op
  hexroyale.chooseteam:
    default: true